[project]
name = "Housing Price Dashboard"
version = "0.1.0"
port = 8501
slug = "preswald-project-357027"
entrypoint = "hello.py"



[branding]
name = "Housing Price"
primaryColor = "#FFFFFF"

[datasources.Housing]
type = "csv"
path = "data/Housing.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"